### ISSUE TITLE
NOT display anything under IE 11

### ISSUE THREAD

**Issue by hn82123** [jzlxiaohei/mobx-antd-startar#1]
IE11 console said ‘The startsWith method is not supported.’

I think the antd should be polyfilled.

**Comment by hn82123** [comment]
fixed with https://github.com/ant-design/ant-design/issues/3359

**Comment by jzlxiaohei** [comment]
nice. I have no chance to work with IE11. Sorry that.
fortunately `Antd` fixed it,  so close this issue
